[package]
name = "httpshare"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.2.0", features = ["cargo"] }
regex = "1.11.1"
time = "0.3.36"

[features]
debug = []
